---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install prereqs 
  - pip install https://github.com/ansible/ansible/archive/devel.tar.gz
  - pip install openshift

  # Start OpenShift
  - docker run --publish 8443:8443 -d --name openshift openshift/origin:v3.6.0 start master --listen https://0.0.0.0:8443
  - sleep 15 

  # Fetch a copy of the kube config file
  - docker exec -it openshift cat /var/lib/origin/openshift.local.config/master/admin.kubeconfig >tests/konfig.json

  # Install the current commit to tests/roles. 
  - ansible-galaxy install -p tests/roles git+https://github.com/${TRAVIS_REPO_SLUG}.git,${TRAVIS_COMMIT}

script:
  - cd tests
  - ansible-playbook -vvv -i inventory test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
