# tasks/main.yml
---

- name: Intall latest openshift client 
  pip:
    name: git+https://github.com/openshift/openshift-restclient-python.git#egg=openshift 
    state: latest 
    virtualenv: "{{ virtualenv }}"
  when: install_python_requirements

