plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection:
    kubectl:
      description: Execute tasks in pods running on Kubernetes.
      name: kubectl
      version_added: null
  httpapi: {}
  inventory:
    k8s:
      description: Kubernetes (K8s) inventory source
      name: k8s
      version_added: null
    openshift:
      description: OpenShift inventory source
      name: openshift
      version_added: null
  lookup:
    k8s:
      description: Query the K8s API
      name: k8s
      version_added: null
  module:
    helm:
      description: Manages Kubernetes packages with the Helm package manager
      name: helm
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: 0.11.0
    helm_info:
      description: Get information from Helm package deployed inside the cluster
      name: helm_info
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: 0.11.0
    helm_repository:
      description: Add and remove Helm repository
      name: helm_repository
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: 0.11.0
    k8s:
      description: Manage Kubernetes (K8s) objects
      name: k8s
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: null
    k8s_auth:
      description: Authenticate to Kubernetes clusters which require an explicit login
        step
      name: k8s_auth
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: null
    k8s_exec:
      description: Execute command in Pod
      name: k8s_exec
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: 0.10.0
    k8s_info:
      description: Describe Kubernetes (K8s) objects
      name: k8s_info
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: null
    k8s_log:
      description: Fetch logs from Kubernetes resources
      name: k8s_log
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: 0.10.0
    k8s_scale:
      description: Set a new size for a Deployment, ReplicaSet, Replication Controller,
        or Job.
      name: k8s_scale
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: null
    k8s_service:
      description: Manage Services on Kubernetes
      name: k8s_service
      namespace: .ansible.collections.ansible_collections.community.kubernetes.plugins.modules
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 0.11.0
