---
- name: Ensure helm is not install
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/helm"

- name: Check failed if helm is not install
  include_tasks: test_helm_not_installed.yml

- name: "Install {{ helm_version }}"
  include_tasks: install.yml

- name: Check if failed when tiller is not installed
  include_tasks: test_missing_tiller.yml
  when: "helm_version.startswith('v2')"

- name: Install tiller
  include_tasks: tiller.yml
  when: "helm_version.startswith('v2')"

- name: Deploy charts
  include_tasks: "tests_chart/{{ test_chart_type }}.yml"
  loop_control:
    loop_var: test_chart_type
  with_items:
    - from_local_path
    - from_repository
    - from_url

- name: Clean tiller
  include_tasks: tiller.yml
  vars:
    status: absent
  when: "helm_version.startswith('v2')"

- name: Clean helm install
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/helm/"
